name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:
        env:
          secret_username: ${{ secrets.DOCKERHUB_USERNAME }}
          secret_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: actions/checkout@v2
      - run: docker login -u "$secret_username" -p "$secret_password"
      - run: docker build -t abdir/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true abdir/react-test npm test

      - run: docker build -t abdir/multi-client ./client
      - run: docker build -t abdir/multi-nginx ./nginx
      - run: docker build -t abdir/multi-server ./server
      - run: docker build -t abdir/mutli-worker ./worker

      - run: docker push abdir/multi-client
      - run: docker push abdir/multi-nginx
      - run: docker push abdir/multi-server
      - run: docker push abdir/multi-worker
