name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t abdir/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true cygnetops/react-test npm test

      - run: docker build -t abdir/multi-client ./client
      - run: docker build -t abdir/multi-nginx ./nginx
      - run: docker build -t abdir/multi-server ./server
      - run: docker build -t abdir/mutli-worker ./worker

      - run: docker push abdir/multi-client
      - run: docker push abdir/multi-nginx
      - run: docker push abdir/multi-server
      - run: docker push abdir/multi-worker
